use bevy::prelude::*;
use rand::{thread_rng, Rng};
// Package components to be defined here.

#[derive(Component, Clone, Debug)]
pub struct Package {
    pub recipient_name: String,
    pub street_address: String,
    pub country: String,
    pub zip_code: u32,
    pub weight: f32,
    pub hazmat: bool,
}

impl Package {
    pub fn new() -> Self {
        let rand_num_name = thread_rng().gen_range(0..NAMES.len());
        let rand_num_street = thread_rng().gen_range(0..STREET_NAMES.len());

        let rand_num_countries = thread_rng().gen_range(0..COUNTRIES.len());

        let rand_num_zips = thread_rng().gen_range(0..ZIP_CODES.len());

        let rand_weight: f32 = thread_rng().gen_range(0.0..150.0);

        Package {
            recipient_name: NAMES[rand_num_name].to_string(),
            street_address: STREET_NAMES[rand_num_street].to_string(),
            country: COUNTRIES[rand_num_countries].to_string(),
            zip_code: ZIP_CODES[rand_num_zips],
            weight: rand_weight,
            hazmat: false,
        }
    }
}

pub const NAMES: [&str; 104] = [
    "Alden Mireles",
    "Briar Wainwright",
    "Cressida Nightingale",
    "Daxton Pendleton",
    "Elsie Fairchild",
    "Finnian Lockhart",
    "Gwendolyn Thorne",
    "Hollis Blackwood",
    "Ivy Hawthorne",
    "Jasper Ravenscroft",
    "Kieran Ashford",
    "Lorelei St. Claire",
    "Matthias Whitaker",
    "Nola Sinclair",
    "Ophelia Kingsley",
    "Phineas Montague",
    "Quinlan Hartley",
    "Rowan Everhart",
    "Sylvie Winters",
    "Thaddeus Fox",
    "Ulysses Beaumont",
    "Vesper Nightshade",
    "Wren Holloway",
    "Xander Sterling",
    "Yara Ravenswood",
    "Zephyr Hawthorn",
    "Aurelia Graves",
    "Bastian Draven",
    "Clementine Ashwood",
    "Dante Blackwell",
    "Emberlyn Frost",
    "Felix Nightingale",
    "Gemma Silverton",
    "Hawthorne Sinclair",
    "Isadora Vale",
    "Julius Whitmore",
    "Katalina Ravenscroft",
    "Lysander Thorne",
    "Maeve Blackwood",
    "Nikolai Evergreen",
    "Olivier Hart",
    "Persephone Stone",
    "Quincy Hawthorne",
    "Rhiannon Ashcroft",
    "Sebastian Wilde",
    "Theodora Nightshade",
    "Ursula Fairchild",
    "Valerian St. Claire",
    "Willow Wisteria",
    "Xiomara Delgado",
    "Yves Montague",
    "Zara Winchester",
    "Alistair Hawthorn",
    "Briar Rosewood",
    "Cassius Darkwood",
    "Dahlia Ravensong",
    "Ezekiel Blackthorn",
    "Fleur Nightengale",
    "Gideon Cross",
    "Hazel Woodrow",
    "Iris Ashbourne",
    "Jude Winterbourne",
    "Kira Silvermoon",
    "Lachlan Thistlewood",
    "Morrigan Bloodworth",
    "Nathaniel Irons",
    "Octavia Storm",
    "Percival Ravenshaw",
    "Quinn Redwood",
    "Rosalind Frost",
    "Soren Nightfall",
    "Tamsin Moonshadow",
    "Uriel Darkwater",
    "Violet Everglen",
    "Wilder Ash",
    "Xanthe Nightingale",
    "Yvaine Silverstream",
    "Zephyrine Dusk",
    "Artemis Blackthorne",
    "Bellatrix Thorne",
    "Cedric Stone",
    "Darcy Wilder",
    "Eleanor Darkwood",
    "Finnegan Asher",
    "Genevieve Sterling",
    "Hector Blackwood",
    "Isolde Winterbourne",
    "Jasper Ravenswood",
    "Kendra Silverleaf",
    "Lysandra Nightshade",
    "Maximus Hawthorne",
    "Niamh Evergreen",
    "Orion Storm",
    "Penelope Nightengale",
    "Quintus Frost",
    "Rosalie Moon",
    "Sylvan Darkholme",
    "Thalia Bloodmoon",
    "Ulysses Ravenscroft",
    "Vivienne Shadow",
    "Wolfgang Blackthorn",
    "Xenia Nightingale",
    "Yasmine Silverwood",
    "Zephyr Frost",
];

pub const STREET_NAMES: [&str; 96] = [
    "1234 Elm Street",
    "5678 Maple Avenue",
    "9101 Oak Lane",
    "2468 Pine Road",
    "1357 Cedar Court",
    "8642 Birch Drive",
    "9753 Willow Way",
    "3146 Juniper Street",
    "7890 Sycamore Boulevard",
    "2345 Cherry Lane",
    "6789 Magnolia Avenue",
    "1011 Acacia Road",
    "1213 Poplar Court",
    "1415 Hawthorn Lane",
    "1617 Laurel Street",
    "1819 Walnut Avenue",
    "2021 Birchwood Drive",
    "2223 Pinecrest Road",
    "2425 Spruce Lane",
    "2627 Cedarwood Boulevard",
    "2829 Elmwood Avenue",
    "3031 Redwood Court",
    "3233 Aspen Lane",
    "3435 Willowcrest Drive",
    "3637 Oakwood Avenue",
    "3839 Maplewood Road",
    "4041 Birchcrest Lane",
    "4243 Sycamore Street",
    "4445 Juniper Avenue",
    "4647 Magnolia Boulevard",
    "4849 Hickory Lane",
    "5051 Dogwood Drive",
    "5253 Cedar Avenue",
    "5455 Pinecrest Court",
    "5657 Willow Lane",
    "5859 Birchwood Avenue",
    "6061 Elmwood Road",
    "6263 Maple Street",
    "6465 Oak Avenue",
    "6667 Pine Way",
    "6869 Spruce Lane",
    "7071 Aspen Drive",
    "7273 Cedarwood Court",
    "7475 Sycamore Boulevard",
    "7677 Juniper Lane",
    "7879 Magnolia Road",
    "8081 Hickory Avenue",
    "8283 Dogwood Lane",
    "8485 Birchcrest Court",
    "8687 Elm Street",
    "8889 Maple Avenue",
    "9091 Oak Lane",
    "9293 Pine Road",
    "9495 Cedar Court",
    "9697 Willow Way",
    "9899 Juniper Street",
    "1112 Sycamore Boulevard",
    "1314 Cherry Lane",
    "1516 Magnolia Avenue",
    "1718 Acacia Road",
    "1920 Poplar Court",
    "2122 Hawthorn Lane",
    "2324 Laurel Street",
    "2526 Walnut Avenue",
    "2728 Birchwood Drive",
    "2930 Pinecrest Road",
    "3132 Spruce Lane",
    "3334 Cedarwood Boulevard",
    "3536 Elmwood Avenue",
    "3738 Redwood Court",
    "3940 Aspen Lane",
    "4142 Willowcrest Drive",
    "4344 Oakwood Avenue",
    "4546 Maplewood Road",
    "4748 Birchcrest Lane",
    "4950 Sycamore Street",
    "5152 Juniper Avenue",
    "5354 Magnolia Boulevard",
    "5556 Hickory Lane",
    "5758 Dogwood Drive",
    "5960 Cedar Avenue",
    "6162 Pinecrest Court",
    "6364 Willow Lane",
    "6566 Birchwood Avenue",
    "6768 Elmwood Road",
    "6970 Maple Street",
    "7172 Oak Avenue",
    "7374 Pine Way",
    "7576 Spruce Lane",
    "7778 Aspen Drive",
    "7980 Cedarwood Court",
    "8182 Sycamore Boulevard",
    "8384 Juniper Lane",
    "8586 Magnolia Road",
    "8788 Hickory Avenue",
    "8990 Dogwood Lane",
];

pub const COUNTRIES: [&str; 195] = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Côte d'Ivoire",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

pub const ZIP_CODES: [u32; 92] = [
    12345, 23456, 34567, 45678, 56789, 67890, 78901, 89012, 90123, 01234, 13579, 24680, 35791,
    46802, 57913, 68024, 79135, 80246, 91357, 02468, 97531, 86420, 75319, 64208, 53197, 42086,
    31975, 20864, 09753, 98642, 79853, 67532, 56421, 45312, 34201, 23190, 12039, 01569, 35982,
    46809, 57890, 69012, 79123, 80234, 91345, 02456, 13579, 97531, 86420, 75319, 64208, 53197,
    42086, 31975, 20864, 09753, 98642, 79853, 67532, 56421, 45312, 34201, 23190, 12039, 01569,
    35982, 46809, 57890, 69012, 79123, 80234, 91345, 02456, 13579, 24680, 35791, 46802, 57913,
    68024, 79135, 80246, 91357, 02468, 97531, 86420, 75319, 64208, 53197, 42086, 31975, 20864,
    09753,
];
